# Site settings
title: Nero's Blog
SEOTitle: Nero's Blog | 學習筆記
header-img: img/home-bg.jpg
email: nerocube.tw@gmail.com
description: "Learn programming from life; Learn life from programming"
keyword: "Nero, 後端開發, 學習筆記, Node.js, Python, Golang, Android"
url: "https://nerocube.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
# weibo_username:     nerocube
# zhihu_username:     nerocube
github_username:    nerocube
twitter_username:   nero_chen_
facebook_username:  edge937
linkedin_username:  冠廷-陳-6508b7155



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  parse_block_html: true                # allow kramdown to parse inside html blocks
  toc_levels: 1..6



# Disqus settings
disqus_username: nerocube

# Netease setttings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "從生活中學習編程 ; 從編程中學習生活， <br>The kernenl of life is conviction inspired by deep thinking"
sidebar-avatar: /img/avatar-nero.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    # {
    # #     title: "Su",
    # #     href: "http://su.gallery/"
    # # },{
    #     title: "乱序",
    #     href: "http://mida.re/"
    # }
]
