baseurl = "https://nerocube.github.io"
title = "Nero's Blog"
theme = "hugo-theme-nerocube"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = "nerocube"
googleAnalytics = "UA-137719130-1"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/home-bg.jpg"
  SEOTitle = "Nero's Blog"
  description = "Learn programming from life; Learn life from programming"
  keyword = "Nero, Machine Learning, 學習筆記, GCP, AWS, AI, Data, Python"
  slogan = "Stay Hungry, Stay Foolish"

  image_404 = "img/404-bg.jpg"
  title_404 = "Nothing be found :("
  omit_categories = false

  # leancloud storage for page view counter
  page_view_conter = true 
  leancloud_app_id = "EIu9SR3XRNEeWF1hwxuNhRoF-MdYXbMMI"
  leancloud_app_key = "OaSHpqwJKlCKbUcscyBjI8xk"

  # algolia site search
  algolia_search = true
  algolia_appId = "2Y51GBXPU5"
  algolia_indexName = "nerocube"
  algolia_apiKey = "804dcfa39d9949d2a96915e2d64685b7"

  # Sidebar settings
  sidebar_about_description = "Data Scientist, Open Source Enthusiast and Life Adventurer"
  #sidebar_avatar = "img/avatar-nero.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar = "img/avatar-nero.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  # Twikoo comments
  # Follow https://twikoo.js.org/ to set up your own env_id
  twikoo_env_id = ""

  friends = false
  bookmarks = false
  about_me = true

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.giscus]
  data-repo="NeroCube/nerocube.github.io"
  data-repo-id="MDEwOlJlcG9zaXRvcnkxMjU5MDY4MzU="
  data-category="Q&A"
  data-category-id="DIC_kwDOB4Evk84CREnw"
  data-mapping="pathname"
  data-strict="0"
  data-reactions-enabled="1"
  data-emit-metadata="0"
  data-input-position="bottom"
  data-theme="preferred_color_scheme"
  data-lang="zh-TW"
  crossorigin="anonymous"


  [params.social]
  rss            = true 
  email          = "nerocube.tw@gmail.com"
  facebook      = "https://www.facebook.com/edge937/"
  #googleplus    = "full profile url in googleplus"
  twitter       = "https://twitter.com/nero_cube"
  linkedin       = "https://www.linkedin.com/in/nero-chen-6508b7155"
  #stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/NeroCube"
  #wechat         = "your wechat qr code image"
  #medium        = "full profile url in medium"
  #slack         = "full workspace url in slack"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"
  
  [[params.friend_link]]
  #title = "Linda的博客"
  #href =  "https://zhaozhihan.com"

  [[params.bookmark_link]]
  title =  "Martin Fowler"
  href =  "https://martinfowler.com"
  [[params.bookmark_link]]
  title = "ServiceMesher"
  href =  "http://www.servicemesher.com"
  [[params.bookmark_link]]
  title =  "Pxhere"
  href = "https://pxhere.com"
  [[params.bookmark_link]]
  title = "unsplash"
  href = "https://unsplash.com"
  
  [[params.addtional_menus]]
  title =  "ARCHIVE"
  href =  "/archive/"
  #[[params.addtional_menus]]
  #title =  "NOTES"
  #href =  "/notes/"
  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
theme = "hugo-theme-nerocube"
